name: navi_uxr_example
description: Navi - UXR - Login/Logout/Sign-up Routing - Deep link
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  faker: ^2.0.0-rc

  flutter:
    sdk: flutter

  navi: any

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  navi:
    path: ../../../navi

flutter:
  uses-material-design: true
