name: navi
description: A simple and easy to learn declarative navigation framework for Flutter, based on Navigator 2.0.
version: 0.2.2
homepage: https://github.com/zenonine/navi

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  get_it: ^6.1.0
  mockito: ^5.0.0
  test: ^1.16.0