name: navi
description: Navigation framework for Flutter
version: 0.0.1
author: Zeno Nine <zenonine.com@gmail.com>
homepage: https://github.com/zenonine/navi

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
