name: navi
description: A declarative navigation framework for Flutter, based on Navigator 2.0.
version: 0.0.6
homepage: https://github.com/zenonine/navi

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
