# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: navi

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - run: dart --version
      - run: flutter --version

      - name: Config flutter environment
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter packages get

      - name: Verify formatting
        run: flutter format --set-exit-if-changed lib test

#      - name: Analyze project source
#        run: flutter analyze --fatal-infos

#      - name: Run tests
#        run: flutter test
