# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: navi

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - run: flutter config --no-analytics
      - run: flutter --version

      - name: Install dependencies
        run: flutter packages get

      - name: Verify formatting
        run: flutter format --set-exit-if-changed lib test

      - name: Source code static analysis
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - uses: codecov/codecov-action@v2
        with:
          files: ./navi/coverage/lcov.info
          fail_ci_if_error: true
